name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4

      - name: Install step
        run: "bun install --frozen-lockfile"

      - name: Build step
        run: "bun run build --preset=deno-deploy"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "yunusefendi-distapp-64"
          entrypoint: "server/index.ts"
          root: ".output"
