name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
    - run: bun run tests
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Setup e2e env
      run: echo "${{ secrets.ENV_TESTS_BASE64 }}" | base64 --decode >> .env
    - run: bun run e2e
