name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
    - run: bun run tests
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - run: bun run e2e
